{% set version = "1.1.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-workflowsets
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/workflowsets_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/workflowsets/workflowsets_{{ version }}.tar.gz
  sha256: db0f138bdca0aba0b3d15caac4fefda81d0d98796560cc80d8e761028de935b6

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-cli
    - r-dplyr >=1.0.0
    - r-generics >=0.1.2
    - r-ggplot2
    - r-glue
    - r-hardhat >=1.2.0
    - r-lifecycle >=1.0.0
    - r-parsnip >=1.2.0
    - r-pillar >=1.7.0
    - r-prettyunits
    - r-purrr
    - r-rlang >=1.1.0
    - r-rsample >=0.0.9
    - r-tibble >=3.1.0
    - r-tidyr
    - r-tune >=1.2.0
    - r-vctrs
    - r-withr
    - r-workflows >=1.1.4
  run:
    - r-base
    - r-cli
    - r-dplyr >=1.0.0
    - r-generics >=0.1.2
    - r-ggplot2
    - r-glue
    - r-hardhat >=1.2.0
    - r-lifecycle >=1.0.0
    - r-parsnip >=1.2.0
    - r-pillar >=1.7.0
    - r-prettyunits
    - r-purrr
    - r-rlang >=1.1.0
    - r-rsample >=0.0.9
    - r-tibble >=3.1.0
    - r-tidyr
    - r-tune >=1.2.0
    - r-vctrs
    - r-withr
    - r-workflows >=1.1.4

test:
  commands:
    - $R -e "library('workflowsets')"           # [not win]
    - "\"%R%\" -e \"library('workflowsets')\""  # [win]

about:
  home: https://workflowsets.tidymodels.org
  dev_url: https://github.com/tidymodels/workflowsets
  license: MIT
  summary: A workflow is a combination of a model and preprocessors (e.g, a formula, recipe, etc.) (Kuhn and Silge (2021) <https://www.tmwr.org/>). In order to try different combinations of these, an object can be created that contains many workflows. There are functions to create workflows en masse as well as training them
    and visualizing the results.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
